services:
  - type: worker
    name: eta-invoice-worker
    env: node
    plan: standard # Use a plan that doesn't sleep for a continuous worker
    buildCommand: "pnpm install && pnpm prisma generate && pnpm build"
    startCommand: "pnpm start:worker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eta-operatives-db # The name of our Render DB instance
          property: connectionString
      - key: NODE_ENV
        value: production
      - fromGroup: eta-credentials # Secret Group for API keys

databases:
  - name: eta-operatives-db
    databaseName: eta_operatives
    user: db_user
    plan: starter # Choose a plan that suits your needs